LIST_OF_ENGLISH_NAMES = {'aaron', 'abbott', 'abby', 'abdul', 'abe', 'abel', 'abigail', 'abraham', 'acevedo', 'acosta',
                         'ada', 'adam', 'adams', 'adan', 'addie', 'adela', 'adele', 'adeline', 'adkins', 'adolfo',
                         'adolph', 'adrian', 'adriana', 'adrienne', 'agnes', 'aguilar', 'aguirre', 'agustin', 'ahmad',
                         'ahmed', 'aida', 'aileen', 'aimee', 'aisha', 'al', 'alan', 'alana', 'alba', 'albert',
                         'alberta', 'alberto', 'alden', 'aldo', 'alec', 'alejandra', 'alejandro', 'alex', 'alexander',
                         'alexandra', 'alexandria', 'alexis', 'alfonso', 'alfonzo', 'alford', 'alfred', 'alfreda',
                         'alfredo', 'ali', 'alice', 'alicia', 'aline', 'alisa', 'alisha', 'alison', 'alissa', 'allan',
                         'allen', 'allie', 'allison', 'allyson', 'alma', 'alonzo', 'alphonse', 'alphonso', 'alston',
                         'alta', 'althea', 'alton', 'alva', 'alvarado', 'alvarez', 'alvaro', 'alvin', 'alyce', 'alyson',
                         'alyssa', 'amado', 'amalia', 'amanda', 'amber', 'amelia', 'amie', 'amos', 'amparo', 'amy',
                         'ana', 'anastasia', 'anderson', 'andre', 'andrea', 'andres', 'andrew', 'andrews', 'andy',
                         'angel', 'angela', 'angelia', 'angelica', 'angelina', 'angeline', 'angelique', 'angelita',
                         'angelo', 'angie', 'anibal', 'anita', 'ann', 'anna', 'annabelle', 'anne', 'annette', 'annie',
                         'annmarie', 'anthony', 'antoine', 'antoinette', 'anton', 'antone', 'antonia', 'antonio',
                         'antony', 'antwan', 'april', 'araceli', 'archie', 'ariel', 'arlene', 'arline', 'armand',
                         'armando', 'armstrong', 'arnold', 'arnulfo', 'aron', 'arron', 'art', 'arthur', 'arturo',
                         'ashlee', 'ashley', 'atkins', 'atkinson', 'aubrey', 'audra', 'audrey', 'august', 'augusta',
                         'augustine', 'augustus', 'aurelia', 'aurelio', 'aurora', 'austin', 'autumn', 'ava', 'avery',
                         'avila', 'avis', 'ayala', 'ayers', 'bailey', 'baird', 'baker', 'baldwin', 'ball', 'ballard',
                         'banks', 'barbara', 'barber', 'barbra', 'barker', 'barlow', 'barnes', 'barnett', 'barney',
                         'barr', 'barrera', 'barrett', 'barron', 'barry', 'bart', 'bartlett', 'barton', 'basil', 'bass',
                         'bates', 'battle', 'bauer', 'baxter', 'beach', 'bean', 'beard', 'beasley', 'beatrice',
                         'beatriz', 'beau', 'beck', 'becker', 'becky', 'belinda', 'bell', 'ben', 'bender', 'benita',
                         'benito', 'benjamin', 'bennett', 'bennie', 'benny', 'benson', 'bentley', 'benton', 'berg',
                         'berger', 'bernadette', 'bernadine', 'bernard', 'bernardo', 'bernice', 'bernie', 'berry',
                         'bert', 'berta', 'bertha', 'bertie', 'beryl', 'bessie', 'best', 'beth', 'bethany', 'betsy',
                         'bette', 'bettie', 'betty', 'bettye', 'beulah', 'beverley', 'beverly', 'bianca', 'bill',
                         'billie', 'billy', 'bird', 'bishop', 'black', 'blackburn', 'blackwell', 'blaine', 'blair',
                         'blake', 'blanca', 'blanchard', 'blanche', 'blankenship', 'blevins', 'bob', 'bobbi', 'bobbie',
                         'bobby', 'bolton', 'bond', 'bonita', 'bonner', 'bonnie', 'booker', 'boone', 'booth', 'boris',
                         'bowen', 'bowers', 'bowman', 'boyd', 'boyer', 'boyle', 'brad', 'bradford', 'bradley', 'bradly',
                         'bradshaw', 'brady', 'branch', 'branden', 'brandi', 'brandie', 'brandon', 'brandy', 'brant',
                         'bray', 'brenda', 'brendan', 'brennan', 'brent', 'brenton', 'bret', 'brett', 'brewer', 'brian',
                         'briana', 'brianna', 'brice', 'bridges', 'bridget', 'bridgett', 'bridgette', 'briggs',
                         'bright', 'brigitte', 'britney', 'britt', 'brittany', 'brittney', 'brock', 'brooke', 'brooks',
                         'brown', 'browning', 'bruce', 'bruno', 'bryan', 'bryant', 'bryce', 'bryon', 'buchanan', 'buck',
                         'buckley', 'buckner', 'bud', 'buddy', 'buford', 'bullock', 'burch', 'burgess', 'burke',
                         'burks', 'burl', 'burnett', 'burns', 'burris', 'burt', 'burton', 'bush', 'butler', 'byers',
                         'byrd', 'byron', 'cabrera', 'cain', 'caitlin', 'calderon', 'caldwell', 'caleb', 'calhoun',
                         'callahan', 'callie', 'calvin', 'camacho', 'cameron', 'camille', 'campbell', 'campos',
                         'candace', 'candice', 'candy', 'cannon', 'cantrell', 'cantu', 'cara', 'cardenas', 'carey',
                         'carissa', 'carl', 'carla', 'carlene', 'carlo', 'carlos', 'carlson', 'carlton', 'carly',
                         'carmela', 'carmella', 'carmelo', 'carmen', 'carmine', 'carney', 'carol', 'carole', 'carolina',
                         'caroline', 'carolyn', 'carpenter', 'carr', 'carrie', 'carrillo', 'carroll', 'carson',
                         'carter', 'carver', 'cary', 'casandra', 'case', 'casey', 'cash', 'cassandra', 'cassie',
                         'castaneda', 'castillo', 'castro', 'catalina', 'catherine', 'cathleen', 'cathryn', 'cathy',
                         'cecelia', 'cecil', 'cecile', 'cecilia', 'cedric', 'celeste', 'celia', 'celina', 'cervantes',
                         'cesar', 'chad', 'chadwick', 'chambers', 'chan', 'chance', 'chandler', 'chandra', 'chaney',
                         'chang', 'chapman', 'charity', 'charlene', 'charles', 'charley', 'charlie', 'charlotte',
                         'charmaine', 'chase', 'chasity', 'chauncey', 'chavez', 'chelsea', 'chen', 'cheri', 'cherie',
                         'cherry', 'cheryl', 'chester', 'chi', 'chris', 'christa', 'christensen', 'christi',
                         'christian', 'christie', 'christina', 'christine', 'christoper', 'christopher', 'christy',
                         'chrystal', 'chuck', 'church', 'cindy', 'clair', 'claire', 'clara', 'clare', 'clarence',
                         'clarice', 'clarissa', 'clark', 'clarke', 'claude', 'claudette', 'claudia', 'claudine',
                         'claudio', 'clay', 'clayton', 'clement', 'clements', 'clemons', 'cleo', 'cleveland', 'cliff',
                         'clifford', 'clifton', 'cline', 'clint', 'clinton', 'clyde', 'cobb', 'cochran', 'cody',
                         'coffey', 'cohen', 'colby', 'cole', 'coleen', 'coleman', 'colette', 'colin', 'colleen',
                         'collier', 'collin', 'collins', 'colon', 'combs', 'compton', 'concepcion', 'concetta',
                         'conley', 'conner', 'connie', 'conrad', 'constance', 'consuelo', 'contreras', 'conway', 'cook',
                         'cooke', 'cooley', 'cooper', 'copeland', 'cora', 'corey', 'corina', 'corine', 'corinne',
                         'cornelia', 'cornelius', 'cornell', 'corrine', 'cortez', 'cory', 'cote', 'cotton', 'courtney',
                         'cox', 'coy', 'craft', 'craig', 'crane', 'crawford', 'cristina', 'crosby', 'cross', 'cruz',
                         'crystal', 'cummings', 'cunningham', 'curry', 'curt', 'curtis', 'cynthia', 'cyril', 'cyrus',
                         'daisy', 'dale', 'dallas', 'dalton', 'damian', 'damien', 'damion', 'damon', 'dan', 'dana',
                         'dane', 'danial', 'daniel', 'danielle', 'daniels', 'dannie', 'danny', 'dante', 'daphne',
                         'darcy', 'daren', 'darin', 'dario', 'darius', 'darla', 'darlene', 'darnell', 'darrel',
                         'darrell', 'darren', 'darrin', 'darryl', 'darwin', 'daryl', 'daugherty', 'dave', 'davenport',
                         'david', 'davidson', 'davis', 'dawn', 'dawson', 'day', 'dean', 'deana', 'deandre', 'deann',
                         'deanna', 'deanne', 'debbie', 'debora', 'deborah', 'debra', 'decker', 'dee', 'deena', 'deidre',
                         'deirdre', 'dejesus', 'delacruz', 'delaney', 'delbert', 'deleon', 'delgado', 'delia', 'della',
                         'delmar', 'delmer', 'delores', 'deloris', 'demetrius', 'dena', 'denis', 'denise', 'dennis',
                         'denny', 'denver', 'deon', 'derek', 'derick', 'derrick', 'desiree', 'desmond', 'devin',
                         'devon', 'dewayne', 'dewey', 'dewitt', 'dexter', 'diana', 'diane', 'diann', 'dianna', 'dianne',
                         'diaz', 'dick', 'dickerson', 'dickson', 'diego', 'dillard', 'dillon', 'dina', 'dino', 'dion',
                         'dionne', 'dirk', 'dixie', 'dixon', 'dodson', 'dollie', 'dolly', 'dolores', 'domingo',
                         'dominguez', 'dominic', 'dominick', 'dominique', 'don', 'dona', 'donald', 'donaldson', 'donn',
                         'donna', 'donnell', 'donnie', 'donny', 'donovan', 'dora', 'doreen', 'dorian', 'doris',
                         'dorothea', 'dorothy', 'dorsey', 'dorthy', 'dotson', 'doug', 'douglas', 'downs', 'doyle',
                         'drake', 'drew', 'duane', 'dudley', 'duffy', 'duke', 'duncan', 'dunlap', 'dunn', 'duran',
                         'durham', 'dustin', 'dusty', 'dwayne', 'dwight', 'dyer', 'dylan', 'earl', 'earle', 'earlene',
                         'earline', 'earnest', 'earnestine', 'eaton', 'ebony', 'ed', 'eddie', 'eddy', 'edgar',
                         'edgardo', 'edith', 'edmond', 'edmund', 'edna', 'eduardo', 'edward', 'edwardo', 'edwards',
                         'edwin', 'edwina', 'effie', 'efrain', 'efren', 'eileen', 'elaine', 'elba', 'elbert', 'eldon',
                         'eleanor', 'elena', 'eli', 'elias', 'elijah', 'elinor', 'elisa', 'elisabeth', 'elise',
                         'eliseo', 'eliza', 'elizabeth', 'ella', 'ellen', 'elliot', 'elliott', 'ellis', 'ellison',
                         'elma', 'elmer', 'elmo', 'elnora', 'eloise', 'eloy', 'elsa', 'elsie', 'elton', 'elva', 'elvia',
                         'elvin', 'elvira', 'elvis', 'elwood', 'emanuel', 'emerson', 'emery', 'emil', 'emile', 'emilia',
                         'emilio', 'emily', 'emma', 'emmanuel', 'emmett', 'emory', 'england', 'english', 'enid',
                         'enrique', 'eric', 'erica', 'erich', 'erick', 'ericka', 'erickson', 'erik', 'erika', 'erin',
                         'erma', 'erna', 'ernest', 'ernestine', 'ernesto', 'ernie', 'errol', 'ervin', 'erwin',
                         'esmeralda', 'esperanza', 'espinoza', 'essie', 'esteban', 'estela', 'estella', 'estelle',
                         'ester', 'estes', 'esther', 'estrada', 'ethan', 'ethel', 'etta', 'eugene', 'eugenia',
                         'eugenio', 'eula', 'eunice', 'eva', 'evan', 'evangelina', 'evangeline', 'evans', 'eve',
                         'evelyn', 'everett', 'everette', 'ewing', 'ezra', 'fabian', 'faith', 'fannie', 'fanny',
                         'farley', 'farmer', 'farrell', 'faulkner', 'faustino', 'fay', 'faye', 'federico', 'felecia',
                         'felicia', 'felipe', 'felix', 'ferdinand', 'ferguson', 'fern', 'fernandez', 'fernando',
                         'ferrell', 'fidel', 'fields', 'figueroa', 'finch', 'finley', 'fischer', 'fisher', 'fitzgerald',
                         'fitzpatrick', 'fleming', 'fletcher', 'flora', 'florence', 'flores', 'florine', 'flossie',
                         'flowers', 'floyd', 'flynn', 'foley', 'forbes', 'ford', 'foreman', 'forest', 'forrest',
                         'foster', 'fowler', 'fox', 'fran', 'frances', 'francesca', 'francine', 'francis', 'francisca',
                         'francisco', 'franco', 'frank', 'frankie', 'franklin', 'franks', 'frazier', 'fred', 'freda',
                         'freddie', 'freddy', 'frederic', 'frederick', 'fredric', 'fredrick', 'freeman', 'freida',
                         'french', 'frieda', 'fritz', 'frost', 'fry', 'frye', 'fuentes', 'fuller', 'fulton', 'gabriel',
                         'gabriela', 'gabrielle', 'gail', 'gaines', 'gale', 'galen', 'gallagher', 'gallegos',
                         'galloway', 'gamble', 'garcia', 'gardner', 'garland', 'garner', 'garrett', 'garrison', 'garry',
                         'garth', 'gary', 'garza', 'gates', 'gavin', 'gay', 'gayle', 'gena', 'genaro', 'gene', 'geneva',
                         'genevieve', 'gentry', 'geoffrey', 'george', 'georgette', 'georgia', 'georgina', 'gerald',
                         'geraldine', 'gerard', 'gerardo', 'german', 'gerry', 'gertrude', 'gibbs', 'gibson', 'gil',
                         'gilbert', 'gilberto', 'gilda', 'giles', 'gill', 'gillespie', 'gilliam', 'gilmore', 'gina',
                         'ginger', 'gino', 'giovanni', 'gladys', 'glass', 'glen', 'glenda', 'glenn', 'glenna', 'gloria',
                         'glover', 'goff', 'golden', 'goldie', 'gomez', 'gonzales', 'gonzalez', 'gonzalo', 'good',
                         'goodman', 'goodwin', 'gordon', 'gould', 'grace', 'gracie', 'graciela', 'grady', 'graham',
                         'grant', 'graves', 'gray', 'green', 'greene', 'greer', 'greg', 'gregg', 'gregorio', 'gregory',
                         'greta', 'gretchen', 'griffin', 'griffith', 'grimes', 'gross', 'grover', 'guadalupe', 'guerra',
                         'guerrero', 'guillermo', 'gus', 'gustavo', 'guthrie', 'gutierrez', 'guy', 'guzman', 'gwen',
                         'gwendolyn', 'hahn', 'hal', 'hale', 'haley', 'hall', 'hallie', 'hamilton', 'hammond',
                         'hampton', 'hancock', 'haney', 'hank', 'hannah', 'hans', 'hansen', 'hanson', 'hardin',
                         'harding', 'hardy', 'harlan', 'harley', 'harmon', 'harold', 'harper', 'harrell', 'harriet',
                         'harriett', 'harrington', 'harris', 'harrison', 'harry', 'hart', 'hartman', 'harvey',
                         'hatfield', 'hattie', 'hawkins', 'hayden', 'hayes', 'haynes', 'hays', 'hazel', 'head', 'heath',
                         'heather', 'hebert', 'hector', 'heidi', 'helen', 'helena', 'helene', 'helga', 'henderson',
                         'hendricks', 'hendrix', 'henrietta', 'henry', 'hensley', 'henson', 'herbert', 'heriberto',
                         'herman', 'herminia', 'hernandez', 'herrera', 'herring', 'herschel', 'hershel', 'hess',
                         'hester', 'hewitt', 'hickman', 'hicks', 'higgins', 'hilario', 'hilary', 'hilda', 'hill',
                         'hillary', 'hines', 'hinton', 'hiram', 'hobbs', 'hodge', 'hodges', 'hoffman', 'hogan',
                         'holcomb', 'holden', 'holder', 'holland', 'hollie', 'hollis', 'holloway', 'holly', 'holman',
                         'holmes', 'holt', 'homer', 'hood', 'hooper', 'hoover', 'hope', 'hopkins', 'hopper', 'horace',
                         'horacio', 'horn', 'horne', 'horton', 'house', 'houston', 'howard', 'howe', 'howell',
                         'hubbard', 'huber', 'hubert', 'hudson', 'huff', 'huffman', 'hugh', 'hughes', 'hugo', 'hull',
                         'humberto', 'humphrey', 'hung', 'hunt', 'hunter', 'hurley', 'hurst', 'hutchinson', 'hyde',
                         'ian', 'ida', 'ignacio', 'ila', 'ilene', 'imelda', 'imogene', 'ina', 'ines', 'inez', 'ingram',
                         'ingrid', 'ira', 'irene', 'iris', 'irma', 'irvin', 'irving', 'irwin', 'isaac', 'isabel',
                         'isabella', 'isabelle', 'isaiah', 'isiah', 'isidro', 'ismael', 'israel', 'issac', 'iva',
                         'ivan', 'ivory', 'ivy', 'jack', 'jackie', 'jacklyn', 'jackson', 'jaclyn', 'jacob', 'jacobs',
                         'jacobson', 'jacqueline', 'jacquelyn', 'jacques', 'jaime', 'jake', 'jamaal', 'jamal', 'jamar',
                         'jame', 'jamel', 'james', 'jami', 'jamie', 'jan', 'jana', 'jane', 'janell', 'janelle', 'janet',
                         'janette', 'janice', 'janie', 'janine', 'janis', 'janna', 'jannie', 'jared', 'jarred',
                         'jarrett', 'jarrod', 'jarvis', 'jasmine', 'jason', 'jasper', 'javier', 'jay', 'jayne',
                         'jayson', 'jean', 'jeanette', 'jeanie', 'jeanine', 'jeanne', 'jeannette', 'jeannie',
                         'jeannine', 'jed', 'jeff', 'jefferey', 'jefferson', 'jeffery', 'jeffrey', 'jeffry', 'jenifer',
                         'jenkins', 'jenna', 'jennie', 'jennifer', 'jennings', 'jenny', 'jensen', 'jerald', 'jeremiah',
                         'jeremy', 'jeri', 'jermaine', 'jerold', 'jerome', 'jerri', 'jerrod', 'jerrold', 'jerry',
                         'jess', 'jesse', 'jessica', 'jessie', 'jesus', 'jewel', 'jewell', 'jill', 'jillian', 'jim',
                         'jimenez', 'jimmie', 'jimmy', 'jo', 'joan', 'joann', 'joanna', 'joanne', 'joaquin', 'jocelyn',
                         'jodi', 'jodie', 'jody', 'joe', 'joel', 'joesph', 'joey', 'johanna', 'john', 'johnathan',
                         'johnathon', 'johnie', 'johnnie', 'johnny', 'johns', 'johnson', 'johnston', 'jolene', 'jon',
                         'jonah', 'jonas', 'jonathan', 'jonathon', 'jones', 'joni', 'jordan', 'jorge', 'jose', 'josef',
                         'josefa', 'josefina', 'joseph', 'josephine', 'josh', 'joshua', 'josiah', 'josie', 'josue',
                         'joy', 'joyce', 'joyner', 'juan', 'juana', 'juanita', 'juarez', 'judith', 'judson', 'judy',
                         'jules', 'julia', 'julian', 'juliana', 'julianne', 'julie', 'juliet', 'juliette', 'julio',
                         'julius', 'june', 'junior', 'justice', 'justin', 'justine', 'kaitlin', 'kane', 'kara',
                         'kareem', 'karen', 'kari', 'karin', 'karina', 'karl', 'karla', 'karyn', 'kasey', 'kate',
                         'katelyn', 'katharine', 'katherine', 'katheryn', 'kathie', 'kathleen', 'kathrine', 'kathryn',
                         'kathy', 'katie', 'katina', 'katrina', 'katy', 'kaufman', 'kay', 'kaye', 'kayla', 'keisha',
                         'keith', 'keller', 'kelley', 'kelli', 'kellie', 'kelly', 'kelsey', 'kelvin', 'kemp', 'ken',
                         'kendall', 'kendra', 'kendrick', 'kennedy', 'kenneth', 'kennith', 'kenny', 'kent', 'kenton',
                         'kenya', 'keri', 'kermit', 'kerr', 'kerri', 'kerry', 'keven', 'kevin', 'key', 'kidd', 'kieth',
                         'kim', 'kimberley', 'kimberly', 'king', 'kinney', 'kip', 'kirby', 'kirk', 'kirkland',
                         'kirsten', 'kitty', 'klein', 'kline', 'knapp', 'knight', 'knowles', 'knox', 'koch', 'kory',
                         'kramer', 'kris', 'krista', 'kristen', 'kristi', 'kristie', 'kristin', 'kristina', 'kristine',
                         'kristopher', 'kristy', 'krystal', 'kurt', 'kurtis', 'kyle', 'lacey', 'lacy', 'ladonna',
                         'lakeisha', 'lakisha', 'lamar', 'lamb', 'lambert', 'lamont', 'lana', 'lancaster', 'lance',
                         'landon', 'landry', 'lane', 'lang', 'langley', 'lanny', 'lara', 'larry', 'larsen', 'larson',
                         'latasha', 'latisha', 'latonya', 'latoya', 'laura', 'laurel', 'lauren', 'laurence', 'lauri',
                         'laurie', 'lavern', 'laverne', 'lavonne', 'lawanda', 'lawrence', 'lawson', 'lazaro', 'le',
                         'lea', 'leach', 'leah', 'leann', 'leanna', 'leanne', 'leblanc', 'lee', 'leigh', 'leila',
                         'lela', 'leland', 'lelia', 'lemuel', 'lena', 'lenard', 'lenny', 'lenora', 'lenore', 'leo',
                         'leola', 'leon', 'leona', 'leonard', 'leonardo', 'leonel', 'leonor', 'leopoldo', 'leroy',
                         'les', 'lesa', 'lesley', 'leslie', 'lessie', 'lester', 'leta', 'letha', 'leticia', 'letitia',
                         'levi', 'levine', 'levy', 'lewis', 'lidia', 'lila', 'lilia', 'lilian', 'liliana', 'lillian',
                         'lillie', 'lilly', 'lily', 'lina', 'lincoln', 'linda', 'lindsay', 'lindsey', 'linwood',
                         'lionel', 'lisa', 'little', 'livingston', 'liz', 'liza', 'lizzie', 'lloyd', 'logan', 'lois',
                         'lola', 'lolita', 'lon', 'long', 'lonnie', 'lopez', 'lora', 'loraine', 'loren', 'lorena',
                         'lorene', 'lorenzo', 'loretta', 'lori', 'lorie', 'lorna', 'lorraine', 'lorrie', 'lott',
                         'lottie', 'lou', 'louella', 'louie', 'louis', 'louisa', 'louise', 'lourdes', 'love', 'lowe',
                         'lowell', 'lowery', 'loyd', 'luann', 'lucas', 'lucia', 'luciano', 'lucien', 'lucile',
                         'lucille', 'lucinda', 'lucio', 'lucy', 'luella', 'luis', 'luisa', 'luke', 'lula', 'luna',
                         'lupe', 'luther', 'luz', 'lydia', 'lyle', 'lyman', 'lynch', 'lynda', 'lynette', 'lynn',
                         'lynne', 'lynnette', 'lyons', 'mabel', 'mable', 'mac', 'macdonald', 'macias', 'mack', 'madden',
                         'maddox', 'madeleine', 'madeline', 'madelyn', 'madge', 'mae', 'magdalena', 'maggie', 'mai',
                         'major', 'malcolm', 'maldonado', 'malinda', 'mallory', 'malone', 'mamie', 'mandy', 'mann',
                         'manning', 'manuel', 'manuela', 'mara', 'marc', 'marcel', 'marcelino', 'marcella', 'marcelo',
                         'marci', 'marcia', 'marcie', 'marco', 'marcos', 'marcus', 'marcy', 'margaret', 'margarita',
                         'margarito', 'margery', 'margie', 'margo', 'margret', 'marguerite', 'mari', 'maria', 'marian',
                         'mariana', 'marianne', 'mariano', 'maribel', 'maricela', 'marie', 'marietta', 'marilyn',
                         'marina', 'mario', 'marion', 'marisa', 'marisol', 'marissa', 'maritza', 'marjorie', 'mark',
                         'marks', 'marla', 'marlene', 'marlin', 'marlon', 'marquez', 'marquis', 'marquita', 'marsh',
                         'marsha', 'marshall', 'marta', 'martha', 'martin', 'martina', 'martinez', 'marty', 'marva',
                         'marvin', 'mary', 'maryann', 'maryanne', 'maryellen', 'marylou', 'mason', 'massey', 'mathew',
                         'mathews', 'mathis', 'matilda', 'matt', 'matthew', 'matthews', 'mattie', 'maude', 'maura',
                         'maureen', 'maurice', 'mauricio', 'mauro', 'mavis', 'max', 'maxine', 'maxwell', 'may', 'mayer',
                         'maynard', 'mayo', 'mayra', 'mays', 'mcbride', 'mccall', 'mccarthy', 'mccarty', 'mcclain',
                         'mcclure', 'mcconnell', 'mccormick', 'mccoy', 'mccray', 'mccullough', 'mcdaniel', 'mcdonald',
                         'mcdowell', 'mcfadden', 'mcfarland', 'mcgee', 'mcgowan', 'mcguire', 'mcintosh', 'mcintyre',
                         'mckay', 'mckee', 'mckenzie', 'mckinney', 'mcknight', 'mclaughlin', 'mclean', 'mcleod',
                         'mcmahon', 'mcmillan', 'mcneil', 'mcpherson', 'meadows', 'meagan', 'medina', 'megan', 'meghan',
                         'mejia', 'mel', 'melanie', 'melba', 'melendez', 'melinda', 'melisa', 'melissa', 'melody',
                         'melton', 'melva', 'melvin', 'mendez', 'mendoza', 'mercado', 'mercedes', 'mercer', 'meredith',
                         'merle', 'merlin', 'merrill', 'merritt', 'mervin', 'meyer', 'meyers', 'mia', 'micah',
                         'michael', 'micheal', 'michel', 'michele', 'michelle', 'mickey', 'middleton', 'miguel', 'mike',
                         'milagros', 'mildred', 'miles', 'milford', 'millard', 'miller', 'millicent', 'millie', 'mills',
                         'milo', 'milton', 'mindy', 'minerva', 'minnie', 'miranda', 'miriam', 'misty', 'mitch',
                         'mitchel', 'mitchell', 'mitzi', 'mohamed', 'mohammad', 'mohammed', 'moises', 'molina',
                         'mollie', 'molly', 'mona', 'monica', 'monique', 'monroe', 'monte', 'montgomery', 'montoya',
                         'monty', 'moody', 'moon', 'mooney', 'moore', 'morales', 'moran', 'moreno', 'morgan', 'morin',
                         'morris', 'morrison', 'morrow', 'morse', 'morton', 'moses', 'mosley', 'moss', 'mueller',
                         'mullen', 'mullins', 'munoz', 'muriel', 'murphy', 'murray', 'myers', 'myles', 'myra', 'myrna',
                         'myron', 'myrtle', 'nadia', 'nadine', 'nancy', 'nanette', 'nannie', 'naomi', 'napoleon',
                         'nash', 'natalia', 'natalie', 'natasha', 'nathan', 'nathaniel', 'navarro', 'neal', 'ned',
                         'neil', 'nelda', 'nell', 'nellie', 'nelson', 'nestor', 'nettie', 'neva', 'newman', 'newton',
                         'nguyen', 'nicholas', 'nichole', 'nichols', 'nicholson', 'nick', 'nickolas', 'nicolas',
                         'nicole', 'nielsen', 'nieves', 'nigel', 'nikki', 'nina', 'nita', 'nixon', 'noah', 'noble',
                         'noe', 'noel', 'noelle', 'noemi', 'nola', 'nolan', 'nona', 'nora', 'norbert', 'norberto',
                         'noreen', 'norma', 'norman', 'normand', 'norris', 'norton', 'numbers', 'nunez', 'obrien',
                         'ochoa', 'oconnor', 'octavio', 'odell', 'odessa', 'odis', 'odom', 'odonnell', 'ofelia', 'ola',
                         'olen', 'olga', 'olin', 'olive', 'oliver', 'olivia', 'ollie', 'olsen', 'olson', 'omar',
                         'oneal', 'oneil', 'oneill', 'opal', 'ophelia', 'ora', 'orlando', 'orr', 'ortega', 'ortiz',
                         'orval', 'orville', 'osborn', 'osborne', 'oscar', 'osvaldo', 'otis', 'otto', 'owen', 'owens',
                         'pablo', 'pace', 'pacheco', 'padilla', 'page', 'paige', 'palmer', 'pam', 'pamela', 'pansy',
                         'park', 'parker', 'parks', 'parrish', 'parsons', 'pasquale', 'pat', 'pate', 'patel', 'patrica',
                         'patrice', 'patricia', 'patrick', 'patsy', 'patterson', 'patti', 'patton', 'patty', 'paul',
                         'paula', 'paulette', 'pauline', 'payne', 'pearl', 'pearlie', 'pearson', 'peck', 'pedro',
                         'peggy', 'pena', 'penelope', 'pennington', 'penny', 'percy', 'perez', 'perkins', 'perry',
                         'pete', 'peter', 'peters', 'petersen', 'peterson', 'petra', 'petty', 'phelps', 'phil',
                         'philip', 'phillip', 'phillips', 'phoebe', 'phyllis', 'pickett', 'pierce', 'pierre', 'pittman',
                         'pitts', 'pollard', 'polly', 'poole', 'pope', 'porfirio', 'porter', 'potter', 'potts',
                         'powell', 'powers', 'pratt', 'preston', 'price', 'prince', 'priscilla', 'pruitt', 'puckett',
                         'pugh', 'queen', 'quentin', 'quincy', 'quinn', 'quinton', 'rachael', 'rachel', 'rachelle',
                         'rae', 'rafael', 'ralph', 'ramirez', 'ramiro', 'ramon', 'ramona', 'ramos', 'ramsey', 'randal',
                         'randall', 'randell', 'randi', 'randolph', 'randy', 'raphael', 'raquel', 'rasmussen',
                         'ratliff', 'raul', 'ray', 'raymond', 'raymundo', 'reba', 'rebecca', 'rebekah', 'reed', 'reese',
                         'reeves', 'refugio', 'reggie', 'regina', 'reginald', 'reid', 'reilly', 'reinaldo', 'rena',
                         'rene', 'renee', 'reuben', 'reva', 'rex', 'reyes', 'reyna', 'reynaldo', 'reynolds', 'rhea',
                         'rhoda', 'rhodes', 'rhonda', 'ricardo', 'rice', 'rich', 'richard', 'richards', 'richardson',
                         'richie', 'richmond', 'rick', 'rickey', 'rickie', 'ricky', 'rico', 'riddle', 'riggs',
                         'rigoberto', 'riley', 'rios', 'rita', 'rivas', 'rivera', 'rivers', 'roach', 'rob', 'robbie',
                         'robbins', 'robby', 'roberson', 'robert', 'roberta', 'roberto', 'roberts', 'robertson',
                         'robin', 'robinson', 'robles', 'robt', 'robyn', 'rocco', 'rocha', 'rochelle', 'rocky', 'rod',
                         'roderick', 'rodger', 'rodgers', 'rodney', 'rodolfo', 'rodrick', 'rodrigo', 'rodriguez',
                         'rodriquez', 'rogelio', 'roger', 'rogers', 'rojas', 'roland', 'rolando', 'rolland', 'rollins',
                         'roman', 'romeo', 'romero', 'ron', 'ronald', 'ronda', 'ronnie', 'ronny', 'roosevelt', 'rory',
                         'rosa', 'rosales', 'rosalie', 'rosalind', 'rosalinda', 'rosalyn', 'rosanna', 'rosanne',
                         'rosario', 'roscoe', 'rose', 'roseann', 'rosella', 'rosemarie', 'rosemary', 'rosendo',
                         'rosetta', 'rosie', 'roslyn', 'ross', 'roth', 'rowe', 'rowena', 'rowland', 'roxanne', 'roxie',
                         'roy', 'royal', 'royce', 'ruben', 'rubin', 'ruby', 'rudolph', 'rudy', 'rufus', 'ruiz',
                         'rupert', 'rush', 'russ', 'russel', 'russell', 'russo', 'rusty', 'ruth', 'ruthie', 'rutledge',
                         'ryan', 'sabrina', 'sadie', 'sal', 'salas', 'salazar', 'salinas', 'sallie', 'sally',
                         'salvador', 'salvatore', 'sam', 'samantha', 'sammie', 'sammy', 'sampson', 'samuel', 'sanchez',
                         'sanders', 'sandoval', 'sandra', 'sandy', 'sanford', 'sang', 'santana', 'santiago', 'santos',
                         'sara', 'sarah', 'sargent', 'sasha', 'saul', 'saunders', 'saundra', 'savage', 'savannah',
                         'sawyer', 'schmidt', 'schneider', 'schroeder', 'schultz', 'schwartz', 'scot', 'scott',
                         'scottie', 'scotty', 'sean', 'sears', 'sebastian', 'selena', 'sellers', 'selma', 'serena',
                         'sergio', 'serrano', 'seth', 'sexton', 'seymour', 'shaffer', 'shana', 'shane', 'shanna',
                         'shannon', 'shari', 'sharlene', 'sharon', 'sharp', 'sharpe', 'sharron', 'shaun', 'shauna',
                         'shaw', 'shawn', 'shawna', 'sheena', 'sheila', 'shelby', 'sheldon', 'shelia', 'shelley',
                         'shelly', 'shelton', 'shepard', 'shepherd', 'sheppard', 'sheree', 'sheri', 'sherman', 'sherri',
                         'sherrie', 'sherry', 'sheryl', 'shields', 'shirley', 'short', 'sidney', 'silas', 'silva',
                         'silvia', 'simmons', 'simon', 'simone', 'simpson', 'sims', 'singleton', 'skinner', 'slater',
                         'sloan', 'small', 'smith', 'snider', 'snow', 'snyder', 'socorro', 'sofia', 'solis', 'solomon',
                         'son', 'sondra', 'sonia', 'sonja', 'sonny', 'sonya', 'sophia', 'sophie', 'sosa', 'soto',
                         'sparks', 'spears', 'spence', 'spencer', 'stacey', 'staci', 'stacie', 'stacy', 'stafford',
                         'stan', 'stanley', 'stanton', 'stark', 'steele', 'stefan', 'stefanie', 'stein', 'stella',
                         'stephan', 'stephanie', 'stephen', 'stephens', 'stephenson', 'sterling', 'steve', 'steven',
                         'stevens', 'stevenson', 'stevie', 'stewart', 'stokes', 'stone', 'stout', 'strickland',
                         'strong', 'stuart', 'suarez', 'sue', 'sullivan', 'summer', 'summers', 'sung', 'susan',
                         'susana', 'susanna', 'susanne', 'susie', 'sutton', 'suzanne', 'suzette', 'swanson', 'sweeney',
                         'sweet', 'sybil', 'sydney', 'sykes', 'sylvester', 'sylvia', 'tabatha', 'tabitha', 'tad',
                         'talley', 'tamara', 'tameka', 'tamera', 'tami', 'tamika', 'tammi', 'tammie', 'tammy', 'tamra',
                         'tania', 'tanisha', 'tanner', 'tanya', 'tara', 'tasha', 'tate', 'taylor', 'ted', 'teddy',
                         'terence', 'teresa', 'teri', 'terra', 'terrance', 'terrell', 'terrence', 'terri', 'terrie',
                         'terry', 'tessa', 'thad', 'thaddeus', 'thanh', 'thelma', 'theodore', 'theresa', 'therese',
                         'theron', 'thomas', 'thompson', 'thornton', 'thurman', 'tia', 'tiffany', 'tillman', 'tim',
                         'timmy', 'timothy', 'tina', 'tisha', 'toby', 'tod', 'todd', 'tom', 'tomas', 'tommie', 'tommy',
                         'toni', 'tonia', 'tony', 'tonya', 'torres', 'tory', 'townsend', 'tracey', 'traci', 'tracie',
                         'tracy', 'tran', 'travis', 'trent', 'trenton', 'trevino', 'trevor', 'trey', 'tricia', 'trina',
                         'trinidad', 'trisha', 'tristan', 'troy', 'trudy', 'trujillo', 'truman', 'tucker', 'turner',
                         'twila', 'ty', 'tyler', 'tyree', 'tyrone', 'tyson', 'ulysses', 'underwood', 'ursula',
                         'valarie', 'valdez', 'valencia', 'valentin', 'valentine', 'valenzuela', 'valeria', 'valerie',
                         'van', 'vance', 'vanessa', 'vang', 'vargas', 'vasquez', 'vaughan', 'vaughn', 'vazquez', 'vega',
                         'velasquez', 'velazquez', 'velez', 'velma', 'vera', 'vern', 'verna', 'vernon', 'veronica',
                         'vicente', 'vicki', 'vickie', 'vicky', 'victor', 'victoria', 'villarreal', 'vilma', 'vince',
                         'vincent', 'vinson', 'viola', 'violet', 'virgie', 'virgil', 'virginia', 'vito', 'vivian',
                         'vonda', 'wade', 'wagner', 'waldo', 'walker', 'wall', 'wallace', 'waller', 'walls', 'walsh',
                         'walter', 'walters', 'walton', 'wanda', 'ward', 'ware', 'warner', 'warren', 'washington',
                         'waters', 'watkins', 'watson', 'watts', 'wayne', 'weaver', 'webb', 'weber', 'webster', 'weeks',
                         'weiss', 'welch', 'weldon', 'wells', 'wendell', 'wendi', 'wendy', 'wesley', 'west', 'weston',
                         'wheeler', 'whitaker', 'white', 'whitehead', 'whitfield', 'whitley', 'whitney', 'wiggins',
                         'wilbert', 'wilbur', 'wilburn', 'wilcox', 'wilda', 'wilder', 'wiley', 'wilford', 'wilfred',
                         'wilfredo', 'wilkerson', 'wilkins', 'wilkinson', 'will', 'willa', 'willard', 'william',
                         'williams', 'williamson', 'willie', 'willis', 'wilma', 'wilmer', 'wilson', 'wilton', 'winfred',
                         'winifred', 'winnie', 'winston', 'winters', 'wise', 'witt', 'wm', 'wolf', 'wolfe', 'wong',
                         'wood', 'woodard', 'woodrow', 'woods', 'woodward', 'wooten', 'workman', 'wright', 'wyatt',
                         'wynn', 'xavier', 'yang', 'yates', 'yesenia', 'yolanda', 'yong', 'york', 'young', 'yvette',
                         'yvonne', 'zachariah', 'zachary', 'zachery', 'zamora', 'zane', 'zelma', 'zimmerman'
                         }

LIST_OF_AGE_WORDS = {'old', 'young', 'senior', 'grandfather', 'grandmother', 'parents', 'children',
                     'ancestor', 'child', 'kid', 'brother', 'sister', 'father', 'mother', 'elder'}

LIST_OF_GENDER_WORDS = {'femal', 'male', 'female', 'boy', 'girl', 'man', 'woman'}

LIST_OF_US_STATES = {"aa", "ae", "ak", "al", "ap", "ar", "as", "az", "ca", "co", "ct", "dc", "de",
                     "fl", "fm", "ga", "gu", "hi", "ia", "id", "il", "in", "ks", "ky", "la", "ma",
                     "md", "me", "mh", "mi", "mn", "mo", "mp", "ms", "mt", "nc", "nd", "ne", "nh",
                     "nj", "nm", "nv", "ny", "oh", "ok", "or", "pa", "pr", "pw", "ri", "sc", "sd",
                     "tn", "tx", "ut", "va", "vi", "vt", "wa", "wi", "wv", "wy",
                     "alabama", "armed forces pacific", "arkansas", "american samoa", "arizona",
                     "california", "colorado", "connecticut", "district of columbia", "delaware",
                     "florida", "federated states of micronesia", "georgia", "guam", "hawaii",
                     "iowa", "idaho", "illinois", "indiana", "kansas", "kentucky", "louisiana",
                     "massachusetts", "maryland", "maine", "marshall islands", "michigan",
                     "minnesota", "missouri", "northern mariana islands", "mississippi", "montana",
                     "north carolina", "north dakota", "nebraska", "new hampshire", "new jersey",
                     "new mexico", "nevada", "new york", "ohio", "oklahoma", "oregon",
                     "pennsylvania", "puerto rico", "palau", "rhode island", "south carolina",
                     "south dakota", "tennessee", "texas", "utah", "virginia", "virgin islands",
                     "vermont", "washington", "wisconsin", "west virginia", "wyoming"}

LIST_OF_INSURANCE_NAMES = {"horizon", "united", "medicare", "cbg", "moda", "modahealth",
                           "cigna", "healthcare", "river valley", "bcbsil"}

LIST_OF_TEMPORAL_WORDS = {"date", "time", "month", "week", "day", "hour", "minute", "second"}

# TODO: Add zip codes, organization names
stopword_normalization_map = [(LIST_OF_ENGLISH_NAMES, '<name>'),
                              (LIST_OF_AGE_WORDS, '<age>'),
                              (LIST_OF_GENDER_WORDS, '<gender>'),
                              (LIST_OF_US_STATES, '<location>'),
                              (LIST_OF_INSURANCE_NAMES, '<insurance>'),
                              (LIST_OF_TEMPORAL_WORDS, '<temporal>')]
